title: Viv Reay
email: me@vivreay.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Viv Reay is a freelance web designer with experience in UI design, HTML, CSS, Wordpress, Adobe XD, Illustrator, Photoshop and Indesign.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_path: https://github.com/vivr

pathToBlogImgBin: /assets/img/blog/
pathToProjectImgBin: /assets/img/project/
# Build settings
permalink: pretty
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed
collections:
  projects:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
